backend:
  name: git-gateway

site_url: https://jcmachado.com
display_url: https://jcmachado.com
logo_url: /favicon.ico

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "test"
    label: "Test"

    folder: "data"

    create: true

    fields:
      - label: "Título"
        name: "titulo"
        widget: "string"
