backend:
  name: git-gateway

media_folder: "imagenes"
public_folder: "/imagenes"

collections:
  - name: "test"
    label: "Test"

    folder: "data"

    create: true

    fields:
      - label: "Título"
        name: "titulo"
        widget: "string"
